#!/usr/bin/env bash
# Upload data/precompute/ (Phase B tool response cache) to Kaggle as
# <KAGGLE_USER>/satelliteagent-precompute-v2.
#
# This is the *offline tool response cache* generated by
# scripts/build_precompute_v2.py. Lets Kaggle/offline GRPO serve every tool
# call (compute_index, fetch_band, false_color, classify_change, etc.) from
# disk without re-hitting SimSat / Element84 STAC / Gemini.
#
# Usage:
#   cd kaggle/exp002
#   ./upload.sh                # first time → datasets create
#   UPDATE=1 ./upload.sh       # subsequent → datasets version

set -euo pipefail

EXP_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJ_ROOT="$(cd "$EXP_DIR/../.." && pwd)"
SRC="$PROJ_ROOT/data/precompute"
STAGE="$EXP_DIR/stage"

if [ ! -d "$SRC" ]; then
  echo "FAIL: $SRC missing — run scripts/build_precompute_v2.py first" >&2
  exit 2
fi

echo "[1/3] Refreshing $STAGE from $SRC"
rm -rf "$STAGE"
mkdir -p "$STAGE"
# rsync would be nice but cp -r is fine for a one-shot.
cp -r "$SRC"/. "$STAGE/"
cp "$EXP_DIR/dataset-metadata.json" "$STAGE/"

echo "[2/3] Stage contents:"
du -sh "$STAGE" | sed 's/^/  total: /'
echo "  cases:  $(ls "$STAGE" | grep -v dataset-metadata.json | grep -v '_run_stats.yaml' | wc -l)"
echo "  files:  $(find "$STAGE" -type f | wc -l)"

echo "[3/3] Uploading to Kaggle ..."
if [ "${UPDATE:-0}" = "1" ]; then
  kaggle datasets version -p "$STAGE" -m "${MSG:-update}" --dir-mode zip
else
  kaggle datasets create -p "$STAGE" --dir-mode zip
fi
echo "Done."
