"""Symlink the wildfire SWIR composites generated by detect_wildfire_impl
into a human-friendly directory so the user can browse them visually.

Reads data/eval_wildfire.jsonl + data/canonical_dataset.yaml. For every
evaluated case it computes the same composite_key the tool used (md5 of
lat/lon/date/size_km) and creates a symlink under

  data/wildfire_composites/<gt>__<verdict>__<id>__conf<XX>.png

Usage:
    python scripts/dump_wildfire_composites.py
    python scripts/dump_wildfire_composites.py --copy   # hard-copy instead of symlink
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DERIVED_DIR = ROOT / "data" / "derived"
OUT_DIR     = ROOT / "data" / "wildfire_composites"


def composite_key(lat: float, lon: float, timestamp: str, size_km: float) -> str:
    s = f"wildfire|{lat:.4f}|{lon:.4f}|{timestamp[:10]}|{size_km}"
    return "wf_" + hashlib.md5(s.encode()).hexdigest()[:10]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--jsonl",   default=str(ROOT / "data" / "eval_wildfire.jsonl"))
    ap.add_argument("--canonical", default=str(ROOT / "data" / "canonical_dataset.yaml"))
    ap.add_argument("--out", default=str(OUT_DIR))
    ap.add_argument("--copy", action="store_true",
                    help="hard-copy instead of symlink")
    args = ap.parse_args()

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Build id -> case lookup from canonical
    canon = yaml.safe_load(open(args.canonical, encoding="utf-8"))
    by_id = {c["id"]: c for c in canon.get("cases") or []}

    n_ok = n_missing = 0
    with open(args.jsonl, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            row = json.loads(line)
            cid = row["id"]
            case = by_id.get(cid)
            if case is None:
                n_missing += 1
                continue
            after = case.get("request", {}).get("after_date") or case.get("after_date")
            if not after:
                n_missing += 1
                continue
            ckey = composite_key(
                float(case["lat"]), float(case["lon"]),
                after, float(case.get("size_km", 10.0)),
            )
            src = DERIVED_DIR / f"{ckey}.png"
            if not src.exists():
                n_missing += 1
                continue

            gt = "fire" if row.get("gt_fire") else "no_change"
            verdict = row.get("verdict", "?")
            conf = row.get("fire_confidence") or 0.0
            try:
                conf_pct = int(round(float(conf) * 100))
            except (TypeError, ValueError):
                conf_pct = 0
            name = f"{gt}__{verdict}__{cid}__conf{conf_pct:02d}.png"
            dst = out_dir / name
            if dst.exists() or dst.is_symlink():
                dst.unlink()
            if args.copy:
                shutil.copy2(src, dst)
            else:
                dst.symlink_to(src.resolve())
            n_ok += 1

    print(f"[done] linked {n_ok}, missing {n_missing} → {out_dir}")
    print(f"        breakdown:")
    counts: dict[tuple[str, str], int] = {}
    for p in out_dir.glob("*.png"):
        parts = p.name.split("__")
        if len(parts) >= 2:
            counts[(parts[0], parts[1])] = counts.get((parts[0], parts[1]), 0) + 1
    for (gt, v), n in sorted(counts.items()):
        print(f"          {gt:9s} {v:3s}  {n}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
